### PR TITLE
AHurynovich NodeJS AWS course Task 4 Backend Part

### PR DESCRIPTION
**Pull request by Shagon1k**
## Main task
**Task 4.1 is implemented.**
SQL tables creation scripts could be found in [database-sql/products-ddl.sql](https://github.com/Shagon1k/node-js-aws-be/pull/2/files#diff-ec1caf4d31421e9026b6cc6919847a450dc6cdcf279560957b91c88c666ad5cc) file
SQL tables manipulation scripts could be found in [database-sql/products-dml.sql](https://github.com/Shagon1k/node-js-aws-be/pull/2/files#diff-b9a9d07b56c1beab23476f299a6a292e65587374cc62826b4ead0823ca007e2b) file

**Task 4.2 is implemented.**
**_Lambda links (dev stage):_**
Products List GET - https://h0wel3rkm4.execute-api.eu-west-1.amazonaws.com/dev/products
Product GET - https://h0wel3rkm4.execute-api.eu-west-1.amazonaws.com/dev/products/{productId} (example ID - "ed39a926-d4c3-40d7-b2ef-0b465b6fc525")
**_Lambda links (prod stage):_**
Products List GET: https://j25gzwc0cl.execute-api.eu-west-1.amazonaws.com/prod/products
Product GET: https://j25gzwc0cl.execute-api.eu-west-1.amazonaws.com/prod/products/{productId} (example ID - "ed39a926-d4c3-40d7-b2ef-0b465b6fc525")

**Task 4.3 is implemented.**
**_Lambda links (dev stage):_** 
Products List POST: https://h0wel3rkm4.execute-api.eu-west-1.amazonaws.com/dev/products (body should consists of title,description,imageurl,price,count)
**_Lambda links (prodstage):_** 
Products List POST: https://j25gzwc0cl.execute-api.eu-west-1.amazonaws.com/prod/products (body should consists of title,description,imageurl,price,count)

**FrontEnd Application link:** https://d2zvo2vdnqfgz1.cloudfront.net/
Note: integrated with new lambdas which uses DB data

## Additional (optional) tasks
**+1 - POST/products lambda functions returns error 400 status code if product data is invalid**

**+1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)**

**+1 - All lambdas do console.log for each incoming requests and their arguments**

**+1 - Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa) (https://devcenter.kinvey.com/nodejs/tutorials/bl-transactional-support)**

## Front-end PR
https://github.com/Shagon1k/nodejs-aws-fe/pull/3

## Swagger link
https://app.swaggerhub.com/apis/EPAM279/AliakseiHurynovichAWSProductService/1.0.0-oas3#trial

### CODE REVIEW

**Comment by maximsan** [comment]
image
I was not able to submit post request via postman, but it works from front-end. Could you heck what is wrong ?

**Comment by Shagon1k** [comment]
> image
> I was not able to submit post request via postman, but it works from front-end. Could you heck what is wrong ?

@maximsan seems like incorrect body (count and price should be  a number)

**Comment by maximsan** [comment]
It's my mistake. In postman I changed body.  I did request in you swagger API and has the same error. 
image
Is anything else that I missed ? Check your example in swagger, please

**Comment by Shagon1k** [comment]
> It's my mistake. In postman I changed body. I did request in you swagger API and has the same error.
> image
> Is anything else that I missed ? Check your example in swagger, please

There was a typo in swagger file (descripton -> description). Thank you!

**Pull request merged**
